version: '2'
services:
  web:
    build:
      context: .
      args:
        - LOCAL_BUILD=true
    volumes:
      - .:/app
  chrome:
    image: selenium/standalone-chrome-debug
    volumes:
      - ./test/fixtures/files:/app/test/fixtures/files
